import type { ModelDetail } from "@/schema/model";

export const DEFAULT_MODELS: ModelDetail[] = [
  {
    id: "Xenova/distilbert-base-uncased-mnli",
    name: "Xenova/distilbert-base-uncased-mnli",
    modelPath: "Xenova/distilbert-base-uncased-mnli",
    task: "zero-shot-classification",
    config: {
      device: "auto",
    },
    metadata: {
      description: "A distilled version of BERT fine-tuned on the Multi-Genre Natural Language Inference (MNLI) dataset. This model can determine the relationship between two sentences: entailment, contradiction, or neutral. Because it's trained on MNLI, it's commonly used for zero-shot classification by reframing classification as an NLI task - asking whether the input text entails a hypothesis about a candidate label.",
      huggingfaceUrl: "https://huggingface.co/Xenova/distilbert-base-uncased-mnli",
    },
    loadFiles: {},
    loaded: false,
  },
  {
    id: "Xenova/mobilebert-uncased-mnli",
    name: "Xenova/mobilebert-uncased-mnli",
    modelPath: "Xenova/mobilebert-uncased-mnli",
    task: "zero-shot-classification",
    config: {
      device: "auto",
    },
    metadata: {
      description: "MobileBERT model fine-tuned on MNLI dataset. A lightweight BERT variant optimized for mobile and edge devices while maintaining high performance on natural language inference tasks. Like the DistilBERT version, it's used for zero-shot classification by treating it as an NLI problem, but with better efficiency for resource-constrained environments.",
      huggingfaceUrl: "https://huggingface.co/Xenova/mobilebert-uncased-mnli",
    },
    loadFiles: {},
    loaded: false,
  },
  {
    id: "Xenova/bart-large-cnn",
    name: "Xenova/bart-large-cnn",
    modelPath: "Xenova/bart-large-cnn",
    task: "summarization",
    config: {},
    metadata: {
      description: "BART model fine-tuned for summarization on CNN Daily Mail articles. This model can generate concise summaries of long text documents while preserving key information. It's specifically trained on news articles, making it ideal for summarizing factual content and extracting the most important points from longer texts.",
      huggingfaceUrl: "https://huggingface.co/Xenova/bart-large-cnn",
    },
    loadFiles: {},
    loaded: false,
  },
  {
    id: "Xenova/distilbart-cnn-6-6",
    name: "Xenova/distilbart-cnn-6-6",
    modelPath: "Xenova/distilbart-cnn-6-6",
    task: "summarization",
    config: {},
    metadata: {
      description: "A distilled version of BART optimized for CNN summarization. This smaller model maintains good summarization quality while being more efficient than the full BART model. It's perfect for applications where you need fast summarization without sacrificing too much quality, especially for news and article content.",
      huggingfaceUrl: "https://huggingface.co/Xenova/distilbart-cnn-6-6",
    },
    loadFiles: {},
    loaded: false,
  },
  {
    id: "Xenova/bert-base-multilingual-cased-ner-hrl",
    name: "Xenova/bert-base-multilingual-cased-ner-hrl",
    modelPath: "Xenova/bert-base-multilingual-cased-ner-hrl",
    task: "token-classification",
    config: {},
    metadata: {
      description: "Multilingual BERT model fine-tuned for Named Entity Recognition (NER) on the HRL dataset. Can identify entities like persons, organizations, and locations in multiple languages. This makes it particularly useful for processing international documents, multilingual content, and applications that need to extract structured information from text in various languages.",
      huggingfaceUrl: "https://huggingface.co/Xenova/bert-base-multilingual-cased-ner-hrl",
    },
    loadFiles: {},
    loaded: false,
  },
  {
    id: "Xenova/distilbert-base-uncased-finetuned-sst-2-english",
    name: "Xenova/distilbert-base-uncased-finetuned-sst-2-english",
    modelPath: "Xenova/distilbert-base-uncased-finetuned-sst-2-english",
    task: "sentiment-analysis",
    config: {},
    metadata: {
      description: "A distilled version of BERT fine-tuned for sentiment analysis on the SST-2 dataset. This model can classify text as positive or negative sentiment with high accuracy. It's specifically designed for binary sentiment classification, making it ideal for social media monitoring, customer feedback analysis, and any application requiring quick positive/negative sentiment detection.",
      huggingfaceUrl: "https://huggingface.co/Xenova/distilbert-base-uncased-finetuned-sst-2-english",
    },
    loadFiles: {},
    loaded: false,
  },
  {
    id: "Xenova/bert-base-multilingual-uncased-sentiment",
    name: "Xenova/bert-base-multilingual-uncased-sentiment",
    modelPath: "Xenova/bert-base-multilingual-uncased-sentiment",
    task: "text-classification",
    config: {},
    metadata: {
      description: "Multilingual BERT model fine-tuned for sentiment analysis. Can analyze sentiment in multiple languages, making it useful for international applications. This model is perfect for global businesses, international social media monitoring, and any scenario where you need to understand sentiment across different languages without training separate models for each language.",
      huggingfaceUrl: "https://huggingface.co/Xenova/bert-base-multilingual-uncased-sentiment",
    },
    loadFiles: {},
    loaded: false,
  },
  {
    id: "Xenova/finbert",
    name: "Xenova/finbert",
    modelPath: "Xenova/finbert",
    task: "text-classification",
    config: {},
    metadata: {
      description: "BERT model fine-tuned specifically for financial sentiment analysis. Optimized for analyzing sentiment in financial texts, news, and reports. This model is specialized for financial domain language, making it ideal for analyzing market sentiment, financial news, earnings reports, and any text where understanding financial context is crucial for accurate sentiment assessment.",
      huggingfaceUrl: "https://huggingface.co/Xenova/finbert",
    },
    loadFiles: {},
    loaded: false,
  },
  {
    id: "Xenova/toxic-bert",
    name: "Xenova/toxic-bert",
    modelPath: "Xenova/toxic-bert",
    task: "text-classification",
    config: {},
    metadata: {
      description: "BERT model fine-tuned for toxic comment classification. Can identify various types of toxic content including hate speech, threats, and insults. This model is essential for content moderation, online community management, and any platform that needs to automatically detect and filter harmful content to maintain safe user environments.",
      huggingfaceUrl: "https://huggingface.co/Xenova/toxic-bert",
    },
    loadFiles: {},
    loaded: false,
  },
  {
    id: "Xenova/whisper-tiny",
    name: "Xenova/whisper-tiny",
    modelPath: "Xenova/whisper-tiny",
    task: "automatic-speech-recognition",
    config: {
      device: "auto",
    },
    metadata: {
      description: "Lightweight ONNX-compatible version of OpenAI's Whisper-tiny model optimized for web-based speech transcription. This tiny variant provides quick and efficient automatic speech recognition for multilingual audio, making it perfect for browser-based applications requiring fast speech-to-text conversion without sacrificing too much accuracy.",
      huggingfaceUrl: "https://huggingface.co/Xenova/whisper-tiny",
    },
    loadFiles: {},
    loaded: false,
  },
  {
    id: "Xenova/whisper-small",
    name: "Xenova/whisper-small",
    modelPath: "Xenova/whisper-small",
    task: "automatic-speech-recognition",
    config: {
      device: "auto",
    },
    metadata: {
      description: "ONNX-compatible version of OpenAI's whisper-small model designed for web-based speech transcription. Offers better accuracy than the tiny variant while still maintaining good performance for browser environments. Supports multilingual speech recognition and can transcribe audio directly from URLs, making it ideal for JavaScript applications requiring reliable speech-to-text functionality.",
      huggingfaceUrl: "https://huggingface.co/Xenova/whisper-small",
    },
    loadFiles: {},
    loaded: false,
  },
  {
    id: "Xenova/whisper-tiny.en",
    name: "Xenova/whisper-tiny.en",
    modelPath: "Xenova/whisper-tiny.en",
    task: "automatic-speech-recognition",
    config: {
      device: "auto",
    },
    metadata: {
      description: "English-specific version of OpenAI's Whisper-tiny model optimized for web compatibility using ONNX weights. This lightweight model is specifically trained for English speech recognition and supports flexible transcription options including basic text, timestamps, and word-level timestamp generation. Perfect for English-only applications requiring fast and efficient speech transcription.",
      huggingfaceUrl: "https://huggingface.co/Xenova/whisper-tiny.en",
    },
    loadFiles: {},
    loaded: false,
  },
  {
    id: "onnx-community/whisper-base",
    name: "onnx-community/whisper-base",
    modelPath: "onnx-community/whisper-base",
    task: "automatic-speech-recognition",
    config: {
      device: "auto",
    },
    metadata: {
      description: "ONNX-converted version of OpenAI's Whisper-base model designed for web environments using Transformers.js. This base variant offers improved accuracy over smaller models while remaining suitable for web deployment. Supports multilingual automatic speech recognition and is optimized for real-time speech transcription in browser-based applications.",
      huggingfaceUrl: "https://huggingface.co/onnx-community/whisper-base",
    },
    loadFiles: {},
    loaded: false,
  },
];
