export * from "./SentimentAnalysisFormV2"
export * from "./SummarizeInferenceFormV2"
export * from "./Text2TextGenerationFormV2"
export * from "./TextGenerationFormV2"
export * from "./ZeroShotClassificationFormV2"
export * from "./TokenClassificationFormV2"
export * from "./TextClassificationFormV2"
export * from "./AutomaticSpeechRecognitionFormV2"