/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as expired_appLayout_expiredRouteImport } from './routes/(expired_app)/_layout_expired'
import { Route as appLayoutRouteImport } from './routes/(app)/_layout'
import { Route as appLayoutIndexRouteImport } from './routes/(app)/_layout/index'
import { Route as expired_appLayout_expiredExpiredRouteImport } from './routes/(expired_app)/_layout_expired/expired'
import { Route as appLayoutModelIdRouteImport } from './routes/(app)/_layout/$modelId'

const expired_appRouteImport = createFileRoute('/(expired_app)')()
const appRouteImport = createFileRoute('/(app)')()

const expired_appRoute = expired_appRouteImport.update({
  id: '/(expired_app)',
  getParentRoute: () => rootRouteImport,
} as any)
const appRoute = appRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const expired_appLayout_expiredRoute =
  expired_appLayout_expiredRouteImport.update({
    id: '/_layout_expired',
    getParentRoute: () => expired_appRoute,
  } as any)
const appLayoutRoute = appLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => appRoute,
} as any)
const appLayoutIndexRoute = appLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appLayoutRoute,
} as any)
const expired_appLayout_expiredExpiredRoute =
  expired_appLayout_expiredExpiredRouteImport.update({
    id: '/expired',
    path: '/expired',
    getParentRoute: () => expired_appLayout_expiredRoute,
  } as any)
const appLayoutModelIdRoute = appLayoutModelIdRouteImport.update({
  id: '/$modelId',
  path: '/$modelId',
  getParentRoute: () => appLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof appLayoutIndexRoute
  '/$modelId': typeof appLayoutModelIdRoute
  '/expired': typeof expired_appLayout_expiredExpiredRoute
}
export interface FileRoutesByTo {
  '/': typeof appLayoutIndexRoute
  '/$modelId': typeof appLayoutModelIdRoute
  '/expired': typeof expired_appLayout_expiredExpiredRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)': typeof appRouteWithChildren
  '/(app)/_layout': typeof appLayoutRouteWithChildren
  '/(expired_app)': typeof expired_appRouteWithChildren
  '/(expired_app)/_layout_expired': typeof expired_appLayout_expiredRouteWithChildren
  '/(app)/_layout/$modelId': typeof appLayoutModelIdRoute
  '/(expired_app)/_layout_expired/expired': typeof expired_appLayout_expiredExpiredRoute
  '/(app)/_layout/': typeof appLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$modelId' | '/expired'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$modelId' | '/expired'
  id:
    | '__root__'
    | '/(app)'
    | '/(app)/_layout'
    | '/(expired_app)'
    | '/(expired_app)/_layout_expired'
    | '/(app)/_layout/$modelId'
    | '/(expired_app)/_layout_expired/expired'
    | '/(app)/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRoute: typeof appRouteWithChildren
  expired_appRoute: typeof expired_appRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(expired_app)': {
      id: '/(expired_app)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof expired_appRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)': {
      id: '/(app)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(expired_app)/_layout_expired': {
      id: '/(expired_app)/_layout_expired'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof expired_appLayout_expiredRouteImport
      parentRoute: typeof expired_appRoute
    }
    '/(app)/_layout': {
      id: '/(app)/_layout'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appLayoutRouteImport
      parentRoute: typeof appRoute
    }
    '/(app)/_layout/': {
      id: '/(app)/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appLayoutIndexRouteImport
      parentRoute: typeof appLayoutRoute
    }
    '/(expired_app)/_layout_expired/expired': {
      id: '/(expired_app)/_layout_expired/expired'
      path: '/expired'
      fullPath: '/expired'
      preLoaderRoute: typeof expired_appLayout_expiredExpiredRouteImport
      parentRoute: typeof expired_appLayout_expiredRoute
    }
    '/(app)/_layout/$modelId': {
      id: '/(app)/_layout/$modelId'
      path: '/$modelId'
      fullPath: '/$modelId'
      preLoaderRoute: typeof appLayoutModelIdRouteImport
      parentRoute: typeof appLayoutRoute
    }
  }
}

interface appLayoutRouteChildren {
  appLayoutModelIdRoute: typeof appLayoutModelIdRoute
  appLayoutIndexRoute: typeof appLayoutIndexRoute
}

const appLayoutRouteChildren: appLayoutRouteChildren = {
  appLayoutModelIdRoute: appLayoutModelIdRoute,
  appLayoutIndexRoute: appLayoutIndexRoute,
}

const appLayoutRouteWithChildren = appLayoutRoute._addFileChildren(
  appLayoutRouteChildren,
)

interface appRouteChildren {
  appLayoutRoute: typeof appLayoutRouteWithChildren
}

const appRouteChildren: appRouteChildren = {
  appLayoutRoute: appLayoutRouteWithChildren,
}

const appRouteWithChildren = appRoute._addFileChildren(appRouteChildren)

interface expired_appLayout_expiredRouteChildren {
  expired_appLayout_expiredExpiredRoute: typeof expired_appLayout_expiredExpiredRoute
}

const expired_appLayout_expiredRouteChildren: expired_appLayout_expiredRouteChildren =
  {
    expired_appLayout_expiredExpiredRoute:
      expired_appLayout_expiredExpiredRoute,
  }

const expired_appLayout_expiredRouteWithChildren =
  expired_appLayout_expiredRoute._addFileChildren(
    expired_appLayout_expiredRouteChildren,
  )

interface expired_appRouteChildren {
  expired_appLayout_expiredRoute: typeof expired_appLayout_expiredRouteWithChildren
}

const expired_appRouteChildren: expired_appRouteChildren = {
  expired_appLayout_expiredRoute: expired_appLayout_expiredRouteWithChildren,
}

const expired_appRouteWithChildren = expired_appRoute._addFileChildren(
  expired_appRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appRoute: appRouteWithChildren,
  expired_appRoute: expired_appRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
